server.port=8077
##############################################################
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl 
spring.datasource.username=System  
spring.datasource.password=orcl

##################################################333
#spring.datasource.url=jdbc:oracle:thin:@//nichebitdev.czwgg46wsmg0.ap-south-1.rds.amazonaws.com:1521/DATABASE 
#spring.datasource.username=admin
#spring.datasource.password=Ram$10005
######################################################
#spring.datasource.url=jdbc:h2:mem:Ram_naik
#spring.datasource.username=sa   
#spring.datasource.password=password
#####################################################

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

springdoc.packages-to-scan=com.Nichebit.Controller
springdoc.paths-to-match=/getbook/{id},/getAllBooks,/addBook,/updatBook,/Delete/{id},/getbookById/{bid},/generate-excel-report
